# Generated by Django 5.1.6 on 2025-02-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='religion',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='religion',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
